#!/bin/bash
CREATE_FRAMEWORK=1 bundle exec xcake make

xcodebuild -workspace DemoSwiftInterfaceModuleName.xcworkspace \
  -scheme Library1 \
  -sdk iphonesimulator \
  BUILD_DIR=./build

rm build/Debug-iphonesimulator/Library1.framework/**/Library1.swiftmodule/*.swiftmodule

bundle exec xcake make

