name: Test

jobs:
  specs:
    strategy:
      fail-fast: false

    name: Test
    runs-on: macos-11.6

    steps:
      - name: Checkout git
        uses: actions/checkout@v1


      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 13.1

      - name: Run Tests
        run: ./build_app

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
